
version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - gis_2ban_1_network
    volumes:
      - /home/gis_2ban_1/nginx.conf:/etc/nginx/nginx.conf
      - gis_2ban_1_static:/data/static
      - gis_2ban_1_media:/data/media
    ports:
      - 80:80

  gis_2ban_1_container_gunicorn:
    image: gis_2ban_1_image:v5
    networks:
      - gis_2ban_1_network
    secrets:
      - DJANGO_SECRET_KEY
    volumes:
      - gis_2ban_1_static:/home/gis_2ban_1/staticfiles
      - gis_2ban_1_media:/home/gis_2ban_1/media

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_2ban_1_network
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE : django
      MYSQL_USER : django
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD

networks:
  gis_2ban_1_network:

volumes:
  gis_2ban_1_static:
  gis_2ban_1_media:
  database:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MYSQL_PASSWORD:
    external: true
  MYSQL_ROOT_PASSWORD:
    external: true

