
version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - gis_network
    volumes:
      - /home/django_course/nginx.conf:/etc/nginx/nginx.conf
      - gis_static:/data/static
      - gis_media:/data/media
      - gis_log:/var/log/nginx/
    ports:
      - mode: host
        protocol: tcp
        target: 80
        published: 80

  goaccess:
    image: allinurl/goaccess:1.5.1
    volumes:
    - gis_log:/var/log/nginx/
    ports:
    - 7890:7890
    command: /var/log/nginx/gis_access.log -o /var/log/nginx/report.html --log-format=COMBINED --real-time-html

  django:
    image: gis_2ban_1_image:v5
    networks:
      - gis_network
    secrets:
      - MYSQL_PASSWORD
      - DJANGO_SECRET_KEY
      - MYSQL_USER
    volumes:
      - gis_static:/home/gis_2ban_1/staticfiles
      - gis_media:/home/gis_2ban_1/media

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_network
    volumes:
      - gis_mariadb:/var/lib/mysql
    secrets:
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    environment:
      MYSQL_DATABASE : django
      MYSQL_USER_FILE: /run/secrets/MYSQL_USER
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD

networks:
  gis_network:

volumes:
  gis_static:
  gis_media:
  gis_mariadb:
  gis_log:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MYSQL_PASSWORD:
    external: true
  MYSQL_ROOT_PASSWORD:
    external: true
  MYSQL_USER:
    external: true

